server:
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://192.168.1.22:5432/Microservice
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        show-sql: true
